platform :ios, '17.4'

target 'MoneyMorphApp' do

pod 'CurrencyRequest' , '~> 0.1'

pod 'ActionSheetPicker-3.0', '~> 2.7.4'

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.4'
		end
	end
end
